# https://leetcode.com/problems/find-the-difference/description/?envType=problem-list-v2&envId=string&difficulty=EASY


# 389. Find the Difference

# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.



# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

# Example 2:
# Input: s = "", t = "y"
# Output: "y"
 




# logic:  will find the char using for loop which doesnt exist in s
# s = "abcd"
# t = "abcde"

# s = "ae"
# t = "aea"


s = ""
t = "y"

ans=''

for i in s: 
    if i  in t:
        t=t.replace(i,'',1)
        ans= t
    else:
        ans=t

print(ans)